### ISSUE TITLE
Token image on sheets doesn't work if token images are randomised.

### ISSUE THREAD

**Issue by SalieriC** [SalieriC/SWADE-Spices-Flavours#24]
Should use the individual tokens image if a token is placed and a token character sheet is used or a random one if opened from the sidebar.

**Comment by javierriveracastro** [comment]
Do you mean that the NPC sheet should use the token instead of the actor image?

Or should it only use the token image is it is randomized?

**Comment by SalieriC** [comment]
@javierriveracastro In a perfect world it would use the token image of the actual token from which the sheet was opened. If the Actor sheet is opened it should either randomise the token or use the actor image instead. Any way is fine though because right now it just shows missing image if token image is selected.

**Comment by javierriveracastro** [comment]
Sorry the options are two:

- Always show token image.
- Show token image when it is random, or use actor image otherwise.

Wait... You mean you do randomize actor image, not token image? That's crazy. I'll try to use always the token image.

**Comment by SalieriC** [comment]
no no no.
I don't randomise actor images. That'd be bonkers. But if, in Spices & Flavours settings, token image selected to be shown on the sheets. then the image isn't shown on the sheets if the actor uses randomised token images.

**Comment by javierriveracastro** [comment]
If you mean the image on items sheets, then it's done.

If you mean the image on the sheet, we don't do nothing to it, but I can try.

**Comment by javierriveracastro** [comment]
Changing the image in the npc sheet is easy but have a side effect. It also changes de discrete actor image.

I don't know if it is desirable.

**Comment by SalieriC** [comment]
I think we have a communication problem here. changing the image of the npc sheet is not the problem. The problem is that if the token image is randomised it looks like this on the item sheet (technically on the PC sheet as well but usually one does not randomise token images on a PC sheet I guess): 
![image](https://user-images.githubusercontent.com/1230041/113075721-c9821200-91cd-11eb-813e-a0614abeb80b.png)
I think we could check if the randomise token checkbox is checked and if so use the actor image instead of the token image if the token image is used and not the actor image anyway.

**Comment by javierriveracastro** [comment]
That's solved. Pull.

I have also changed the image in the NPC sheet, so that if token is selected as the character portrait in settings, it uses the token image instead of actor. But that not only changes the image on the sheet, it also changes the image in the "special actor" that is magically created for unlinked tokens, so even if you change the setting back it can't return to the actor image. In truth it does but the actor image is now the same as the token.

You can always drag a new token from the actor sidebar, so this is not a big problem, while if you are using randomize tokens it is very neat. But it is an unexpected behavior, that can be confusing.

This second change is still only in my local copy. What I am asking is: Do I push that second change or do I stash it?

**Comment by SalieriC** [comment]
I don't fully understand. Could you clarify @javierriveracastro?

Also the current change you've made seems to place the actor image on PC owned items even if token image is selected, so that's another bug that came with your changes.

**Comment by javierriveracastro** [comment]
Another?

**Comment by javierriveracastro** [comment]
Anyway, it was happening on linked actor. I have solved it,  but in the same branch than the NPC token portrait thing.

Here is a video that I hope explains the problem.

https://www.webmshare.com/play/5dLe8

Sorry for the external link, github doesn't support webm.

I you can't see the problem in the video, nobody will.

So either, told me to push it or rollback my last commit.

**Comment by SalieriC** [comment]
Oh, so it changes the token sheets actor image to the token image ones? I call that a feature, this is awesome! =)

**Comment by javierriveracastro** [comment]
Yes, but if the sheet is not linked to an actor, it changes it for the good.

Even if you change the configuration it doesn't get back to the actor image for already created tokens. It works for new tokens or tokens with "real" actors.

**Comment by SalieriC** [comment]
I see. Hm. I still kinda like it. I'd say we use it for now and if someone complains we can think about it further.

**Comment by SalieriC** [comment]
It still doesn't seem to work on actors in the sidebar, or am I missing something @javierriveracastro ?

**Comment by javierriveracastro** [comment]
Likely not. It gets the image from the token, so if there is no token it should default to actor image.
