### ISSUE TITLE
Different fonts (feature request)

### ISSUE THREAD

**Issue by parvusdomus** [SalieriC/SWADE-Spices-Flavours#3]
It would be great to have the option to select different fonts to be used in the different parts of the sheet

**Comment by javierriveracastro** [comment]
I have pushed a patch that let's you change the font of the sheet.

The main problem is that your players need to have that font installed or the sheet will default to the browser default.

That means that you should probably restrict yourself to common ones, and even that could fail.

**Comment by javierriveracastro** [comment]
The only other option is using Google Fonts or something like that. But that means:

- Will only work online
- Will make connections to Google for the fonts, and they will log all the data that they can.

**Comment by parvusdomus** [comment]
I suppose I can always make my players install the font in their computers, no problem with that.
The worst that can happen is that they don't and get the default font, so I'm good with that.

**Comment by SalieriC** [comment]
@javierriveracastro: Please do not use something that connects to other services. I would veto against it. Is it not possible to use a font in the servers data structure?

**Comment by SalieriC** [comment]
@all-contributors please add @parvusdomus for ideas.

**Comment by javierriveracastro** [comment]
Can I close this? If we are not going to use Google Fonts, I believe it's done.

**Comment by parvusdomus** [comment]
Sure, you can close it, no problem (I think local font is more than enough for me).
