### ISSUE TITLE
Logo and Actor Image, too small

### ISSUE THREAD

**Issue by smoothingplane** [SalieriC/SWADE-Spices-Flavours#37]
is there a possibility to insert the size of the headline section to enlarge the logo and the image of the actor?

**Comment by javierriveracastro** [comment]
It should be possible.

**Comment by javierriveracastro** [comment]
I have made a attempt try an uploaded it to a new [branch](https://github.com/SalieriC/SWADE-Spices-Flavours/tree/header-heigth)

**Comment by SalieriC** [comment]
@javierriveracastro it seems that it increases the header size only but doesn't adjust anything beyond that. It doesn't seem to change the dimensions of the logo or actor image.

**Comment by javierriveracastro** [comment]
Hummm.... looks like I took this bug too literal.

**Comment by javierriveracastro** [comment]
Ok, another attempt.

https://user-images.githubusercontent.com/8113700/113590615-2bf66a80-9633-11eb-8e51-817f91f0eb99.mp4

**Comment by javierriveracastro** [comment]
This one is not configurable right now and makes the header section taller by default if you are using a portrait image (I mean not landscape) as portrait.

**Comment by SalieriC** [comment]
@smoothingplane is that what you had in mind? I thought about configurable size of the images but apparently this request isn't so clear.
@javierriveracastro is it possible to make it toggleable?

**Comment by javierriveracastro** [comment]
Yes, but it is probably more work that it is valuable and also not pretty. Right now it just a css hack. To make it toggleable it will need javascript injecting inline css. Ugly. But certainly possible.

**Comment by javierriveracastro** [comment]
>  I thought about configurable size of the images but apparently this request isn't so clear.

There is no way of changing the image sizes by just changing the header height, nor is it possible to make then bigger without wither changing header size or making other things smaller. The only way ahead is to make the sheet both wider and taller, but this will impact everything not just the header.

**Comment by smoothingplane** [comment]
Sorry for answering just now, however this is much better!

**Comment by SalieriC** [comment]
Okay, would you merge it @javierriveracastro then? =)
(Pull before you do. This would wrap up the 0.5.0 release I think.)

**Comment by javierriveracastro** [comment]
Sure, sorry for this delay, but this last two weeks have been just working and sleeping.

**Comment by javierriveracastro** [comment]
Merged, not time right now to check that everything works together, so be careful. I'll try to snap half an hour in the afternoon..
