### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by montver** [SalieriC/SWADE-Spices-Flavours#4]
It would be interesting to be able to change the background color of the sheet, give it a touch of another color if the image is transparent

**Comment by SalieriC** [comment]
I will try but can't promise anything at this point.

**Comment by SalieriC** [comment]
Done. Expect it in v.0.2.0 soon-ish. Good catch btw. =)

**Comment by SalieriC** [comment]
@all-contributors please add @montver for ideas.

**Comment by SalieriC** [comment]
@all-contributors please add @montver for ideas.
