### ISSUE TITLE
SWADE 0.17.x compatibility

### ISSUE THREAD

**Issue by SalieriC** [SalieriC/SWADE-Spices-Flavours#45]
Some things break on 0.17.x of the system. Please collect here what you encounter.

- [x] Active Effects On/Off button not coloured anymore
- [x] Skill icons double on the PC sheet (need to remove them for the PC sheet only
- [x] Die types are not alligned (a system bug that FloRad wants to take care of, but listing it here anyway)
- [x] Abilities which are marked as "Grant Powers" do not add the Powers Tab to the sheet.

Please post issues with 0.17.x here if you find some. There will not be another release before system bugs have been patched as 0.17.1 is already planned.

**Comment by javierriveracastro** [comment]
Skill icons done. Do we try to tacke the aligment or wait for Flo?

**Comment by SalieriC** [comment]
I was thinking about this. I'm almost sure Flo will do this but I was thinking about adding a dice icon to the skills depending on their die type. In that light it sure would be good to have a foot in the door so to speak because for that we'd need to allign them anyway. So, if you feel bored, please go ahead. =)

**Comment by javierriveracastro** [comment]
Plemty of thing to do. I'd better wait a couple of days for Flo.

**Comment by SalieriC** [comment]
Since Flo did not adress the skill issue in 0.17.1 I would like to take a look at it with you @javierriveracastro whenever you've got time. Maybe it's an easy fix.

**Comment by SalieriC** [comment]
Also there is a new problem: The PC and NPC sheet does not get the Powers Tab if an ability item type has Grants Powers set to true.

**Comment by SalieriC** [comment]
Did the die stuff but it's rather hacky.
