### ISSUE TITLE
Bottom of the nav tabs are also rounded by the Tab border radius option

### ISSUE THREAD

**Issue by Tenyryas** [SalieriC/SWADE-Spices-Flavours#50]
As discussed in Discord.
You also need to apply the rules to the `.swade.sheet .tabs a.item.active` and `.swade.sheet .tabs .item:hover, .swade.sheet .tabs .item:focus`  css selectors, after your `border-radius: var(--tab_border_radius);` rule, of course.

**Comment by SalieriC** [comment]
Done.
