### ISSUE TITLE
Any plans to upgrade to Foundry v10?

### ISSUE THREAD

**Issue by steveculshaw** [SalieriC/SWADE-Spices-Flavours#55]
Any plans to upgrade to Foundry v10?

_... and any idea if it'll work in v10?_

**Comment by SalieriC** [comment]
It won't even work on v9 unfortunately. Unfortunately, development is currently stopped. If and when we will revive it is uncertain.

**Comment by steveculshaw** [comment]
Ah well :-(

But thanks for all the other SWADE modules ... just starting on getting to grips with SWIM :-)
