### ISSUE TITLE
Show skill icons on official character sheet

### ISSUE THREAD

**Issue by eXaminator** [SalieriC/SWADE-Spices-Flavours#6]
It would be good if the option to display skill icons would also enable them for the official character sheet. Or add another option specifically for the official sheet.

**Comment by SalieriC** [comment]
I'm sorry, but we don't want to touch the official sheet any more than we already did. I'm even torn apart on the Bennies. I'd advise you to keep a backup of the original skill icons module. That being said, it is currently planned for the core system anyway: https://gitlab.com/peginc/swade/-/issues/187

**Comment by SalieriC** [comment]
@all-contributors please add @eXaminator for ideas.
