### ISSUE TITLE
Feature Request: better visual for active effect on/off toggle

### ISSUE THREAD

**Issue by Alis-72** [SalieriC/SWADE-Spices-Flavours#8]
Love your work!
Small feature request: current toggle for active effects in character sheet is visually a bit vague, difference with 'on' or 'off' state is too small to see quickly (for us with old eyes).
It would be awesome if that could be made visually more prominent. Maybe slider button  or play/pause icons?

**Comment by SalieriC** [comment]
I like the idea. I was thinking about something like this:
![image](https://user-images.githubusercontent.com/1230041/107016904-ca369300-679e-11eb-86d1-8955841a7e20.png)
And before you ask: Yes, I was thinking of colouring the off  red but I don't know how to do that yet, I need to do more research on if and how it is possible.
Changing the button itself seems difficult I have no idea how I would do that at all. The solution with the colour however is easy when I force it on the user. An optional solution ultimately comes down to learning css variables first and thus is tied to #5. When I can get the hang of it, I should be able to do it.
Anyhow, what do you think of colorising it the way in the screenshot @Alis-72, would that be alright for you?

**Comment by Alis-72** [comment]
Coloring works great for me. Not so great for color-blind persons, though accessibility might be something for different module.

**Comment by SalieriC** [comment]
Good point. That would be something for Foundry itself I suppose. Maybe create an issue for changing the image of it on Foundrys GitLab?: https://gitlab.com/foundrynet/foundryvtt
I think accessability should be something on everyones concern right now but I think it is better suited for the core software.

**Comment by Alis-72** [comment]
I'll create new ticket there.
This ticket just became obsolete.

**Comment by SalieriC** [comment]
Closed by accident. Will still try to figure out a way to colorise it, as I think it'd be super cool. ^^

**Comment by SalieriC** [comment]
Okay, done. It's not optional atm but will hopefully be once I figure out how CSS variables work. Will keep this issue open for the time being.
![image](https://user-images.githubusercontent.com/1230041/107049707-b56ff480-67ca-11eb-8e98-121b1db2c8c4.png)

**Comment by SalieriC** [comment]
@javierriveracastro came up with an additional idea that hopefully also works for colourblind people. What do you think @Alis-72?
![image](https://user-images.githubusercontent.com/1230041/107073763-0e9a5100-67e8-11eb-80f7-dfd9d44053e9.png)

**Comment by SalieriC** [comment]
@all-contributors please add @Alis-72 for a11y (accessibility issues) and ideas.

**Comment by SalieriC** [comment]
@all-contributors please add @Alis-72 for a11y (accessibility issues) and ideas.
